baseurl = "http://davojan.ru/"
languageCode = "ru-ru"
title = "/davojan/register"
theme = "redlounge"

disqusShortname = "davojan"

[[menu.main]]
  weight = 1
  name = "Обо мне"
  url = "/about/"

[[menu.main]]
  weight = 2
  name = "Спорт"
  url = "/sports/"

[[menu.main]]
  weight = 3
  name = "Гиковское"
  url = "/tech/"

[[menu.main]]
  weight = 4
  name = "Архив"
  url = "/archive/"


[[menu.social]]
  pre = "<i class='fa fa-twitter-square'></i>"
  url = "http://www.twitter.com/davojan"
  identifier = "twitter"

[[menu.social]]
  pre = "<i class='fa fa-facebook-square'></i>"
  url = "https://www.facebook.com/david.galoyan"
  identifier = "facebook"

[[menu.social]]
  pre = "<i class='fa fa-github-square'></i>"
  url = "https://github.com/davojan"
  identifier = "github"

[[menu.social]]
  pre = "<i class='fa fa-rss-square'></i>"
  url = "http://feeds.feedburner.com/davojan"
  identifier = "rss"
